spring.application.name=myWeb

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/spring}

spring.datasource.username=${DB_USERNAME:root}

spring.datasource.password=${DB_PASSWORD:2025}

server.servlet.session.tracking-modes=cookie

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6379
spring.session.store-type=redis

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_fU4po9Mm5